name: Akamai DS2 Dataflow Pipeline

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - "*.drawio"
      - ".gitignore"
      - "*.md"
      - "banner.txt"
      - "deploy.sh"
      - "/grafana/*"
      - "/iac/*.tf"
      - "/iac/*.sh"
      - "LICENSE"
      - "undeploy.sh"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Download the project files.
        uses: actions/checkout@v3

      - name: Setting up environment.
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Build services.
        run: ./build.sh

      - name: Package services.
        run: ./package.sh

      - name: Publish services.
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./publish.sh
